version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Installing SAM CLI..."
      - pip install aws-sam-cli

  build:
    commands:
      - echo "Build started on `date`"
      - sam build

  post_build:
    commands:
      - echo "Deploying the application..."
      - sam deploy --no-confirm-changeset --capabilities CAPABILITY_IAM