AWSTemplateFormatVersion: "2010-09-09"
Description: >-
  This role is assumed by CloudFormation to manage EC2 resources.
  It has the necessary permissions to create/delete EC2 instances, security groups, etc.

Resources:
  EC2ManagementRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: CfnServiceRole-CsvToEc2
      # このロールを引き受けられるサービスとしてCloudFormationを信頼する
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
            Action: sts:AssumeRole
      # EC2リソースを操作するための全ての権限をこちらに集約
      Policies:
        - PolicyName: EC2-Management-Policy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  # EC2リソースの作成・削除・変更に必要な権限
                  - "ec2:RunInstances"
                  - "ec2:TerminateInstances"
                  - "ec2:CreateTags"
                  - "ec2:CreateSecurityGroup"
                  - "ec2:DeleteSecurityGroup"
                  - "ec2:AuthorizeSecurityGroupIngress"
                  - "ec2:RevokeSecurityGroupIngress"
                  # パラメータ検証に必要な権限
                  - "ec2:DescribeImages"
                  - "ec2:DescribeVpcs"
                  - "ec2:DescribeSubnets"
                  - "ec2:DescribeSecurityGroups"
                  - "ec2:DescribeInstances"
                Resource: "*"

Outputs:
  CfnServiceRoleArn:
    Description: The ARN of the CloudFormation service role
    Value: !GetAtt EC2ManagementRole.Arn
    # 他のスタックから参照できるようにARNをエクスポートする
    Export:
      Name: CfnServiceRoleArn-CsvToEc2