AWSTemplateFormatVersion: "2010-09-09"
Description: >
  (Nested Stack) Creates an EC2 instance with an IAM role for SSM access.

Parameters:
  InstanceType:
    Type: String
    Default: t2.micro
    Description: EC2 instance type.
  AmiId:
    Type: AWS::EC2::Image::Id
    Description: The AMI ID for the EC2 instance.
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID to launch the instance in.
  SubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: Subnet ID to launch the instance in.

Resources:
  EC2InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore"

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref EC2InstanceRole

  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: "Security group for the EC2 instance"
      VpcId: !Ref VpcId
      Tags:
        - Key: Name
          Value: !Sub "sg-for-${AWS::StackName}"

  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceType
      ImageId: !Ref AmiId
      SubnetId: !Ref SubnetId
      SecurityGroupIds:
        - !Ref MySecurityGroup
      IamInstanceProfile: !GetAtt EC2InstanceProfile.Arn
      Tags:
        - Key: Name
          Value: !Sub "ec2-${AWS::StackName}"

Outputs:
  InstanceId:
    Description: "Instance ID of the created EC2 instance"
    Value: !Ref MyEC2Instance