version = 0.1

[default.deploy.parameters]
stack_name = "csv-to-ec2"
resolve_s3 = true
s3_prefix = "csv-to-ec2"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "Environment=\"dev\" RetentionDays=\"30\""
image_repositories = []
