# template.yaml
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A simple and refined stack to create an EC2 instance from a CSV file in S3 using Lambda.

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket

  CsvToEc2Function:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-CsvToEc2Function"
      Handler: app.lambda_handler 
      Runtime: python3.13
      Timeout: 60
      CodeUri: src/
      Events:
        S3CsvUpload:
          Type: S3
          Properties:
            Bucket: !Ref S3Bucket
            Events: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: .csv
      Policies:
        - Statement:
            - Effect: Allow
              Action: ec2:RunInstances
              Resource:
                - !Sub "arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:instance/*"
                - !Sub "arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:volume/*"
                - !Sub "arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:network-interface/*"
                - !Sub "arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:security-group/*"
                - !Sub "arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:subnet/*"
                - "arn:aws:ec2:${AWS::Region}::image/*"
            - Effect: Allow
              Action: ec2:CreateTags
              Resource: !Sub "arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:instance/*"
              Condition:
                StringEquals:
                  ec2:CreateAction: "RunInstances"

Outputs:
  S3BucketName:
    Description: "Bucket to upload CSV files. This name is auto-generated."
    Value: !Ref S3Bucket