AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A simple and refined stack to create an EC2 instance from a CSV file in S3 using Lambda.

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    DependsOn: S3InvokePermission
    Properties:
      BucketName: !Sub "csv-ec2-creator-${AWS::AccountId}-${AWS::Region}"
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:*
            Function: !GetAtt CsvToEc2Function.Arn
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: .csv
  CsvToEc2Function:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${AWS::StackName}-CsvToEc2Function"
      Handler: app.lambda_handler
      Runtime: python3.13
      Timeout: 60
      CodeUri: src/
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action: s3:GetObject
              Resource: !Sub "arn:aws:s3:::csv-ec2-creator-${AWS::AccountId}-${AWS::Region}/*"
            - Effect: Allow
              Action: ec2:RunInstances
              Resource:
                - !Sub "arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:instance/*"
                - !Sub "arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:volume/*"
                - !Sub "arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:network-interface/*"
                - !Sub "arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:security-group/*"
                - !Sub "arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:subnet/*"
                - !Sub "arn:aws:ec2:${AWS::Region}::image/*"
            - Effect: Allow
              Action: ec2:CreateTags
              Resource: !Sub "arn:aws:ec2:${AWS::Region}:${AWS::AccountId}:instance/*"
              Condition:
                StringEquals:
                  ec2:CreateAction: "RunInstances"
  S3InvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt CsvToEc2Function.Arn
      Action: lambda:InvokeFunction
      Principal: s3.amazonaws.com
      SourceArn: !Sub "arn:aws:s3:::csv-ec2-creator-${AWS::AccountId}-${AWS::Region}"

Outputs:
  S3BucketName:
    Description: "Bucket to upload CSV files."
    Value: !Ref S3Bucket