AWSTemplateFormatVersion: "2010-09-09"
Description: Deploys the Lambda function for csv-to-ec2.

Parameters:
  S3BucketName:
    Type: String
    Description: Name of the S3 bucket where the Lambda function code is stored.
  S3Key:
    Type: String
    Description: S3 key for the Lambda function's zip file.

Resources:
  MyLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: csv-to-ec2-function
      Runtime: python3.11
      Handler: lambda_function.lambda_handler
      Code:
        S3Bucket: !Ref S3BucketName
        S3Key: !Ref S3Key
      Role: !ImportValue Lambda-csv-to-ec2-Role-Arn
      Timeout: 60
      Environment:
        Variables:
          CFN_SERVICE_ROLE_ARN: !ImportValue CfnServiceRoleArn-CsvToEc2

  MyLambdaFunctionS3Permission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt MyLambdaFunction.Arn
      Action: "lambda:InvokeFunction"
      Principal: "s3.amazonaws.com"
      SourceArn: !Sub "arn:aws:s3:::${S3BucketName}"
      SourceAccount: !Ref "AWS::AccountId"

Outputs:
  LambdaFunctionName:
    Description: "The name of the Lambda function"
    Value: !Ref MyLambdaFunction
  LambdaFunctionArn:
    Description: "The ARN of the Lambda function"
    Value: !GetAtt MyLambdaFunction.Arn
    Export:
      Name: CsvToEc2LambdaFunctionArn
