AWSTemplateFormatVersion: "2010-09-09"
Description: lambda関数をトリガーとするs3バケットのテンプレート

# 手入力でARNを指定
# イベント通知先のlambdaは、再利用できるように
Parameters:
  LambdaFunctionArn:
    Type: String
    Description: The ARN of the Lambda function to trigger.

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "csv-to-ec2-data-${AWS::AccountId}-${AWS::Region}"
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      VersioningConfiguration:
        Status: Enabled
      # イベント通知設定
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: "s3:ObjectCreated:*" # s3にオブジェクトが作られたら通知
            Function: !Ref LambdaFunctionArn # 手入力したlambdaのarn
            Filter:
              S3Key:
                Rules:
                  - Name: suffix
                    Value: ".csv" # csvの場合のみlambdaが動くように指定

Outputs:
  BucketName:
    Description: "Name of the S3 bucket"
    Value: !Ref MyS3Bucket